# Generated by Django 2.2.3 on 2019-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imdb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('moviename', models.CharField(default=' ', max_length=100)),
                ('raing', models.CharField(default=' ', max_length=10)),
                ('star_cast', models.CharField(default=' ', max_length=300)),
            ],
            options={
                'db_table': 'imdb',
            },
        ),
    ]
